### ISSUE TITLE
put style in <pre> for inline-css

### ISSUE THREAD

**Issue by tpapp** [hniksic/emacs-htmlize#10]
When `htmlize-region-for-paste` is used, the background color of the buffer is not used, which can lead to weird-looking outputs (eg with `whitespace-mode`). Please have `inline-css` put style in the `<pre>` tag, like for `<body>`.

**Comment by hniksic** [comment]
Thanks for the PR. The patch looks good, but omitting the background color was intentional, to avoid pasted code snippets forcing their own background different from the rest of the document.

Can you please describe or show the weird-looking `whitespace-mode` output?

**Comment by tpapp** [comment]
I wanted to use `emacs-htmlize` to make something like a screenshot (a more or less exact reproduction of what I see on the screen) of a region, but I understand that some would rather have a transparent background for the reasons above.

I uploaded a [screenshot](http://www.zimagez.com/zimage/screenshot2017-10-0208-41-26.php) with an omitted background, and a [gist](https://gist.github.com/tpapp/748da1c304accf8d4ba453dc30c4ea16) of various outputs. Because I have harmonizing colors in `whitespace-mode`, without a background they look weird.

 Perhaps if I added a customizable option for including style with `<pre>`?

**Comment by tpapp** [comment]
Possibly. Should I make a PR?

**Comment by hniksic** [comment]
Sorry, I meant to write: do you think a "screenshot" *option* or a dedicated command would be more useful?

Either way, please do make a PR, it's a valuable change.

**Comment by tpapp** [comment]
I made a new PR https://github.com/hniksic/emacs-htmlize/pull/12, making the whole change optional, and adding a 'screenshot' function.

**Comment by tpapp** [comment]
Is there anything else I should do to make this PR accepted?

**Comment by hniksic** [comment]
No, I'll merge it when I get back from vacation in a couple of days.
