### ISSUE TITLE
Faces not recognized

### ISSUE THREAD

**Issue by Hi-Angel** [hniksic/emacs-htmlize#13]
I'm using [color-identifiers-mode](https://github.com/ankurdave/color-identifiers-mode/) with some [custom setup](https://github.com/ankurdave/color-identifiers-mode/pull/50/commits/280c8372f952a579ae2c00c9c205d4f4d0172517) to change most of the highlighting from the code. IOW the code highlight I see is drastically different from just the theme in use.

However `htmlize-buffer` makes html which instead looks like the theme in use.

Steps to reproduce:

1. Open `emacs -Q` *(it will open a scratch buffer with a comment)*.
2. Use `load-file` to load `htmlize.el`
3. Execute `(face-remap-add-relative 'font-lock-comment-face '((:weight bold)))`
4. Execute `htmlize-buffer`

Expected result: resulting html should have a `bold` text.
Actual result: bold keyword is ignored.

**Comment by hniksic** [comment]
Thanks for the report; `face-remapping-alist` should now be respected.
