### ISSUE TITLE
Bring htmlize to ELPA

### ISSUE THREAD

**Issue by To1ne** [hniksic/emacs-htmlize#16]
Org mode _needs_ `htmlize` (in some cases) and even complains about it:

>Please install htmlize from https://github.com/hniksic/emacs-htmlize"

I would like it if I could install `htmlize` from the official GNU ELPA.

**Comment by hniksic** [comment]
`htmlize` is currently available on [MELPA](https://melpa.org/#/htmlize). Presumably an upload to ELPA would also be a one-time thing and would then continue tracking the git repository like MELPA does?

**Comment by hniksic** [comment]
@To1ne Can you help out with the process of making htmlize available on GNU ELPA?

**Comment by aminb** [comment]
I believe the first step for inclusion in GNU ELPA is for you the author and any other contributors of non-trivial (usually >15 lines of code) changes to assign their copyright to the FSF (see [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html). Next steps are described [here](https://www.emacswiki.org/emacs/ELPA#toc2).

**Comment by hniksic** [comment]
@aminb Thanks for the clarfication.

As explained in #23, I am currently not interested in assigning the htmlize copyright to the FSF.
