### ISSUE TITLE
htmlize-face-to-fstruct: Symbol's function definition is void: alist-get

### ISSUE THREAD

**Issue by ant-t** [hniksic/emacs-htmlize#17]
The above error happens when I try to run org-html-export-to-html in org-mode in htmlize-20180317.1549.

There is not issue when I use version 1.51.

**Comment by hniksic** [comment]
Which Emacs version are you using?

**Comment by ant-t** [comment]
GNU Emacs 24.5.1

**Comment by hniksic** [comment]
Thanks for the report, I've now fixed the code to use `(cdr (assq ...))` instead of `(alist-get ...)`.
