### ISSUE TITLE
Error (void-variable overlay)

### ISSUE THREAD

**Issue by glipari** [hniksic/emacs-htmlize#18]
Hi,

I have a problem with htmlize. If I open I simple text file, and try to run htmlize on it, I have the following error: 

------->8-------------8<--------
Debugger entered--Lisp error: (void-variable overlays)
  htmlize-sorted-overlays-at(1)
  htmlize-faces-at-point()
  htmlize-buffer-1()
  htmlize-file("~/tmp/prova-org/example.txt")
  call-interactively(htmlize-file record nil)
  command-execute(htmlize-file record)
  execute-extended-command(nil "htmlize-file")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
------->8-------------8<--------

I have emacs 24.5.1, and I use the htmlize package from downloaded from the git. Here is my .emacs:

------->8-------------8<--------
(add-to-list 'load-path "~/elisp/")
(add-to-list 'load-path "~/elisp/org-mode/lisp")
(add-to-list 'load-path "~/elisp/emacs-htmlize" t)

(require 'org)
(org-babel-load-file
 (expand-file-name "minimal_init.org"
                   user-emacs-directory))
------->8-------------8<--------

and here is my minimal_init.org file 

------->8-------------8<--------
#+BEGIN_SRC emacs-lisp
(setq-default)
(setq inhibit-splash-screen t)
#+END_SRC
------->8-------------8<--------

I run into this problem a few days ago when I tried to export a org-mode file containing src code blocks to html. It was working until a few weeks ago, then suddenly this error. For some reason, it seems I am the only one having this problem; nobody else noticed it, or can reproduce it in the org mailing list. 

Can you help me solving this issue? 

Best regards,

Giuseppe Lipari

**Comment by hniksic** [comment]
Should be fixed now in git, please check. You're likely the only one to see it because you're both: a) using Emacs 24, and b) using a very new htmlize.

**Comment by glipari** [comment]
thanks a lot, I appreciate it!
