### ISSUE TITLE
not convert tab to space in pre

### ISSUE THREAD

**Issue by xahlee** [hniksic/emacs-htmlize#21]
is it possible to not convert tab to spaces inside pre tag?

in golang, its a community convention to use tabs, enforced by the bundled tool gofmt.
(and i think tabs are critical in makefile.)

I write tutorials. So my primary use of htmlize is to convert programing language source code to a htmlized form. With golang, this maybe be a minor problem. thanks.

**Comment by hniksic** [comment]
Added the option `htmlize-untabify`, thanks for the suggestion.

**Comment by xahlee** [comment]
thank you. works great. Long time no chat!
