### ISSUE TITLE
htmlize mirror

### ISSUE THREAD

**Issue by hniksic** [hniksic/emacs-htmlize#24]
In issue #23 org mode developers suggested having an official mirror for htmlize, and set one up. This issue is for making this mirror a documented mirror of htmlize source.

**Comment by hniksic** [comment]
@aminb I have pushed a commit (an amend) to github master several hours ago, and I still don't see it on the gogs mirror. Notice the different ID of the first commit in [github](https://github.com/hniksic/emacs-htmlize/commits/master) and [gogs](https://code.orgmode.org/aminb/emacs-htmlize/commits/master). How often does the mirror sync the content?

**Comment by alphapapa** [comment]
@hniksic IIRC, Amin said it syncs every 8 hours.

**Comment by hniksic** [comment]
@alphapapa And indeed, it's now updated.

**Comment by aminb** [comment]
Hi @hniksic, @alphapapa, sorry for the slow reply; I rarely use GitHub anymore.

Indeed, as @alphapapa said, the mirror is updated roughly every 8 hours. Though, it seems like I can customize it to have it more sync frequently, probably up to every 1 hour. Feel free to ping me any time (preferably via [email](https://aminb.org/contact)) if you like a different interval.

**Comment by hniksic** [comment]
@aminb The 8 hour interval is fine with me.

Should I advertise https://code.orgmode.org/aminb/emacs-htmlize as the mirror, or would you like to set up a more official URL? I'm not familiar with other orgmode-hosted mirrors, so it's not obvious if this is the final setup or just a prototype on your part.

**Comment by aminb** [comment]
Cool.

As for the URL, there's nothing special about it. Actually, I'm pretty sure at the moment anyone can sign up on code.orgmode.org. So if you like, please feel free to register and account there and let me know, and I'll transfer the repo to your account there. That way I think Gogs, like GitHub, will setup a redirect to redirect aminb/emacs-htmlize to hniksic/emacs-htmlize.

**Comment by hniksic** [comment]
@aminb It's totally fine that it's not under my name since I'm not maintaining it. :) I was just wondering if we should try to get a more official-sounding URL like code.orgmode.org/mirrors/htmlize. (This would obviously require an action from an orgmode.org administrator.)

Are there other mirrors of github repos at code.orgmode.org?

**Comment by aminb** [comment]
I'm not aware of any other mirrors on code.orgmode.org, but I like that idea :)

I'll reach out to one of the Org maintainers and see if they'd be fine with me setting up a 'mirrors' organization for all the mirrors and transfer the htmlize to it. I'll get back to you on it.

**Comment by hniksic** [comment]
@aminb Great, thanks for looking into it!

**Comment by aminb** [comment]
So I heard from one of the main Org developers but not from the other.

I went ahead and created a `mirrors` org on Org's Gogs instance and transferred the mirror there:
https://code.orgmode.org/mirrors/emacs-htmlize

Though I believe the future goal for Org is to remove dependency on htmlize and use another library whose name I'm blanking on right now.

**Comment by hniksic** [comment]
The mirror is now acknowledged in the file (which was the only place that mentioned github). Please let me know if additional action is needed.
