### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by dunn** [hniksic/emacs-htmlize#3]
Would you mind tagging releases, so MELPA Stable can pick them up? Thanks!

**Comment by hniksic** [comment]
On Sun, Dec 4, 2016 at 5:36 PM, Alex Dunn <notifications@github.com> wrote:

> Would you mind tagging releases, so MELPA Stable can pick them up? Thanks!
>
Sure. Is there a standardized tag naming scheme that I should use? In other
words, how will MELPA know that a tag I push is a release tag?

(Note that the bumping of the release number in htmlize.el is not meant to
mark a finished release.)

**Comment by dunn** [comment]
MELPA will use any git tag that `version-to-list` parses as a valid version string.

**Comment by hniksic** [comment]
Does it work if the version is part of a namespace such as `release`? It seems like a good idea for distinguishing release/... tags from e.g. maint/... branches.

**Comment by dunn** [comment]
If you have a prefix on the tag name you'll need to add a regex filter to the MELPA recipe (see `version-regexp`: https://github.com/melpa/melpa#recipe-format).

But that would be a way to only send e.g., `stable-1.49` to MELPA Stable, and not `devel-1.49a`.

**Comment by hniksic** [comment]
Created a pull request with the filter, https://github.com/melpa/melpa/pull/4437
