### ISSUE TITLE
Package cl is deprecated

### ISSUE THREAD

**Issue by A6GibKm** [hniksic/emacs-htmlize#33]
```lisp
(require 'loadhist)
(file-dependents (feature-file 'cl))
```
Shows that htmlize/htmlize.elc depends on cl which is deprecated in emacs 27.

EDIT: I made I typo on `(feature-file 'htmlize)`, it was `cl`

**Comment by wasamasa** [comment]
See also #22 which should fix this.

**Comment by hniksic** [comment]
#22 is merged, so I'm closing this.
