### ISSUE TITLE
Wrong number of arguments error

### ISSUE THREAD

**Issue by rhinton** [hniksic/emacs-htmlize#38]
I downloaded the code from:
https://github.com/hniksic/emacs-htmlize
master branch commit dd27bc3f

I'm running:
GNU Emacs 24.3.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.30) of 2018-11-02 on x86-01.bsys.centos.org

When I try to foramt a buffer with `M-x htmlize-buffer` I get the error:
`nreverse: Wrong number of arguments: overlays-at, 2`

Can you help me?  Thanks!

**Comment by hniksic** [comment]
Thanks for the report. Can you please try <kbd>C-h f overlays-at</kbd> and show the output?

Judging by the error message, your `overlays-at` function doesn't support the second argument. You might need to upgrade your Emacs to a newer version.

**Comment by rhinton** [comment]
`overlays-at is a built-in function in `C source code'.

(overlays-at POS)

Return a list of the overlays that contain the character at POS.`

**Comment by hniksic** [comment]
For me it shows an optional argument `SORTED`, which htmlize needs. Please try upgrading to a newer Emacs - the problem should go away.

**Comment by rhinton** [comment]
I'm on a shared machine, so upgrading isn't an option for me.  Thanks for the diagnosis!

**Comment by hniksic** [comment]
It occurred to me that you could just download the last version that supported pre-25 Emacs, which is not that old - like [version 1.55 here](https://raw.githubusercontent.com/hniksic/emacs-htmlize/release/1.55/htmlize.el).
