### ISSUE TITLE
Request to release version 1.58

### ISSUE THREAD

**Issue by suhail-singh** [hniksic/emacs-htmlize#54]
@hniksic , @yantar92 , @tarsius :

This issue affects both `melpa-stable` as well as `nongnu` ELPA.  The latest
version available on both is 1.56, from three years ago.  Since then, a fix for
issue #49 has been merged which fixes an issue when exporting SVG images.

As noted in #36 , while `melpa-stable` uses tagged commits, `nongnu` ELPA uses
commits that increment the version tag in the package header to identify new
(stable) versions.

Could version ~~`1.57`~~ `1.58` be released and made available (preferably on
both, but even if only on `melpa-stable` it would be okay)?

**Comment by hniksic** [comment]
I've now bumped the version to 1.58, since 1.57 was already there, and tagged it. Please let me know if this fixes the issue, and sorry about the delay.

**Comment by tarsius** [comment]
You forgot to push the tag. That aside,

> I've now bumped the version to 1.58, since 1.57 was already there, and tagged it.

This is the way.

(The commit that bumps the embedded version string, is the one which should be tagged with that same version string. Kinda obvious, but too many people don't realize that.)
