### ISSUE TITLE
Org bundles an outdated version of htmlize

### ISSUE THREAD

**Issue by tarsius** [hniksic/emacs-htmlize#7]
Org bundles an old version of `htmlize.el`, which identifies itself as 1.43. The version in this repository is 1.51.

- @bzg as with some other libraries you have already removed, I think this one should be removed too.
- `org-agenda.el`, `ox-org.el`, and `ox-html.el` require `htmlize`. It would probably be a good idea to check whether those libraries are compatible with 1.51.
- @hniksic Assuming that you are an Org user, then I would like to encourage you to do that.

Thanks everyone!

**Comment by hniksic** [comment]
I am not (yet) an org user, but `htmlize` has tried to steer away from backward-incompatible changes, so it would surprise me if there was any incompatibilities between org and the newer version of `htmlize`.

**Comment by tarsius** [comment]
Great!

**Comment by tarsius** [comment]
@bzg Sounds like you can remove `htmlize.el`. Any concerns or did this just fall through the cracks?

**Comment by bzg** [comment]
The thing is some core core Org functions (like e.g. `org-agenda-write`) depend on htmlize.el being required. Since Org is not always installed as a package, how can we deal with this? Throw a warning at `make` time?  Throw a warning within functions requiring `htmlize.el`?

**Comment by tarsius** [comment]
> Throw a warning at make time?

I would go with that approach, though the `(require 'htmlize)` would actually cause an error. You could be a bit more informative like so:

```lisp
(or (require 'htmlize nil t)
    (error "Please install htmlize from https://github.com/hniksic/emacs-htmlize"))
```

**Comment by tarsius** [comment]
> The thing is some core core Org functions (like e.g. org-agenda-write) depend on htmlize.el being required. Since Org is not always installed as a package, how can we deal with this?

The version of Org that is part of Emacs has the same issue. So if you did not get any complains or questions about that in the past, then that would imply that users are able to figure out what to do when `htmlize` cannot be required.

But since Emacs contains Org libraries that require `htmlize`, I think the best solution would be to add it to Emacs itself. The Emacs maintainers might reply that it should be added to GNU Elpa instead. I agree that would make most sense, but as long as Org is part of emacs.git, I think `htmlize` should be added there too.

That of course assumes that @hniksic would be willing to assign the copyright to the FSF and that someone would volunteer to do the work.

**Comment by bzg** [comment]
I'm still for removing `htmlize` from Org's contrib directory, it is done in master (see [this commit](http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=d0ced98).

I'm all for htmlize being available as a package on GNU ELPA or elsewhere, maybe we can ask on the orgmode mailing list for someone to help on this.

**Comment by tarsius** [comment]
Thanks a lot!
